name: Unit tests Windows

on:
  push:
    branches:
    - develop
    - master
  pull_request:
  schedule:
  - cron: '0 0 1 * *'

jobs:
  WinVS2019:
    name: Windows VS2019
#    runs-on: windows-2019
    runs-on: windows-2016
    strategy:
      fail-fast: false
      matrix:
        configuration: [error_code, status_code]
    env:
      NAME: WinVS2019-${{ matrix.configuration }}
          
    steps:
    - uses: actions/checkout@v2

    - name: CMake tests Windows
      shell: bash
      run: |
       if [ "${{ matrix.configuration }}" = "status_code" ]; then
         export CMAKE_CONFIGURE_OPTIONS="-DLLFIO_USE_EXPERIMENTAL_SG14_STATUS_CODE=ON"
       fi
       ctest -S .ci.cmake -VV --timeout 900 "-DCTEST_CONFIGURE_OPTIONS=$CMAKE_CONFIGURE_OPTIONS;CTEST_CMAKE_GENERATOR=\"Visual Studio 15 2019 Win64\"" -DCTEST_SITE=$NAME
      
    - name: Upload Prebuilt Binaries
      uses: actions/upload-artifact@v2
      with:
        name: Windows VS2019 ${{ matrix.configuration }} prebuilt binaries
        path: llfio-v2.0-binaries-win64.zip
      
    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: Windows VS2019 ${{ matrix.configuration }} test results
        path: prebuilt/merged_junit_results.xml

  publish-test-results:
    name: "Publish Unit Tests Results"
    needs: [WinVS2019]
    runs-on: ubuntu-latest
    if: success() || failure()

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          path: artifacts

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1.3
        with:
          check_name: Unit Test Results
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: '**/merged_junit_results.xml'
